image: Visual Studio 2017

environment:
  SHFBROOT:  C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
  SandCastleZipFile: SHFBInstaller.zip
  SandCastleUri: https://github.com/EWSoftware/SHFB/releases/download/v2017.1.28.0/SHFBInstaller_v20171.28.0.zip
  
install:
  - choco install gitversion.portable -pre -y
  - ps: Start-FileDownload $env:SandCastleUri -FileName $env:SandCastleZipFile
  - cmd: 7z x SHFBInstaller.zip -y
  - ps: msiexec /i InstallResources\SandcastleHelpFileBuilder.msi /quiet /qn /norestart /log install.log


before_build:
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

configuration: Release

build_script:
  - ps: .\build.ps1 -Target Compile -ScriptArgs '-nugetVersion="$Env:GitVersion_NuGetVersion"'
  
after_test:
  - ps: .\build.ps1 -Target DistNoTest -ScriptArgs '-nugetVersion="$Env:GitVersion_NuGetVersion"'

artifacts:
  - path: 'dist\%GitVersion_NuGetVersion%\*.nupkg'
  - path: 'dist\%GitVersion_NuGetVersion%\doc\*.chm'
  - path: 'dist\%GitVersion_NuGetVersion%\*.zip'
 
 deploy:
   - provider: GitHub
     description: 'VDS.Common $(GitVersion_SemVer)'
     auth_token:
       secure: 9uAqwz07wsvnlfr0vvwMLRU0sTRg9mDN+CR+UcNQq3G34mBmsE/witNYuI2u8WVC
     on:
       appveyor_repo_tag: false
     artifact: /.*\.nupkg/, /.*\.zip/, /.*\.chm/
